### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by SpawnPPC** [tetracorp/tetracorp.github.io#1]
Greetings. I apologize for using this method to contact you but I can't find anything that allows me to write to you.

I'm interested in disassembling some titles.

I wish I could write to you privately for more details and information.

Thank you.

Emanuel

**Comment by tetracorp** [comment]
The Tetracorp page is only for my own disassembly projects. If you want to disassemble other games, I recommend to start your own project on GitHub.

**Comment by SpawnPPC** [comment]
Ok. Thanx. But is it possible to speak with you by email ?

Thanx.

Emanuele

Il ven 8 set 2023, 00:20 tetracorp ***@***.***> ha scritto:

**Comment by tetracorp** [comment]
Unfortunately not.
