### ISSUE TITLE
Link to page “Intro to Amiga reverse-engineering with Ghidra” on reverse-engineering-amiga.html is dead

### ISSUE THREAD

**Issue by knochenhans** [tetracorp/tetracorp.github.io#2]
Hi, wanted to let you know the link above on the Reverse-engineering Amiga games page is dead. I was only able to find the md source file for the post on github (https://github.com/tetracorp/tetracorp.github.io/blob/main/_posts/2022-05-10-intro-amiga-ghidra.md).

Great write-ups by the way, it’s everything and more one could hope for when delving into this topic, exciting stuff to read!

**Comment by tetracorp** [comment]
Should be fixed now.

Thanks!
